### ISSUE TITLE
Figure needed: Mapping between TIES/ESMACS workflows and RADICAL abstractions

### ISSUE THREAD

**Issue by dww100** [radical-collaboration/isc-htbac-paper#2]
Point here is to show how naturally these two workflows are described by PST abstraction. Also indicate how this is implemented in practice.

**Comment by dww100** [comment]
More generally have you got finalised versions of the figures - if so could you add them in. It will be much easier to adjust the text with these in there.

**Comment by kristofarkas** [comment]
Do you mean the diagrams?

**Comment by jdakka** [comment]
Yes I'll create them today

**Comment by jdakka** [comment]
I'll be modifying this [diagram](https://docs.google.com/drawings/d/1RGN7zL46U6U-qMKDET7PLYzo82pK49DPfKz0FNumeDc/edit?usp=sharing)

**Comment by jdakka** [comment]
Let me know if this [diagram](https://docs.google.com/drawings/d/1RGN7zL46U6U-qMKDET7PLYzo82pK49DPfKz0FNumeDc/edit) is sufficient for mapping the flow between htbac, entk, rp.

**Comment by shantenujha** [comment]
I'm not sure where / what the caption is going to be, so please take with a pinch of salt. 

If the role is, as you say, "mapping the flow between htbac, entk, rp", then the left side of the diagram is redundant.
